// This file contains all the static data for the Cyber Advisor platform.

const certData = {
    oscp: {
        title: " CCNA : Enterprise Networking, Security, and Automation",
        desc: "االمرحلة الأخيرة من CCNA لتأهيلك للاختبار الدولي",
        price: "١٬٦٩٩ ريال",
        org: "CISCO",
        level: "محترف",
        cat: "defensive",
        req: "",
        duration: "90 يوم",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/bwnrPKg",
        image: "assets/Courses/CCNA.png"
    },
    btl1: {
        title: "Introduction to loT and Digital Transformation",
        desc: "دورة لإتقان أساسيات إنترنت الأشياء والتحول الرقمي في بناء المدن الذكية",
        price: "٣٩٩ ريال ",
        org: "CISCO",
        level: "مبتدئ",
        cat: "grc",
        req: "أساسيات الأمن السيبراني",
        duration: "4 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/rRXDOdd",
        image: "assets/Courses/Introduction to loT and Digital Transformation.png"
    },
    security_plus: {
        title: "Introduction to Data Science",
        desc: "دورة للمبتدئين لتأسيسك في أساسيات علم البيانات وتحليلها وربطها بالذكاء الاصطناعي",
        price: "٣٤٩ ريال",
        org: "CISCO",
        level: "مبتدئ",
        cat: "grc",
        req: "Network+ أو خبرة سنتين",
        duration: "3 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/BpEwZmn",
        image: "assets/Courses/Introduction to Data Science.png"
    },
    cissp: {
        title: "IT Essentials 8",
        desc: "تأسيسك في صيانة الحاسب,ادارة انضمة التشغيل,شبكات",
        price: "١٬٢٤٩ ريال",
        org: "CISCO",
        level: "مبتدئ",
        cat: "defensive",
        req: "خبرة 5 سنوات في مجالين أمنيين",
        duration: "6 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/lvzDwEr",
        image: "assets/Courses/IT Essentials 8.png"
    },
    cisa: {
        title: "Cyber Threat Management",
        desc: "مراقبة الشبكات، تحليل التهديدات، والتعامل الفوري مع الحوادث الأمنية",
        price: "٥٤٩ ريال",
        org: "CISCO",
        level: "متوسط",
        cat: "defensive",
        req: "خبرة 5 سنوات في التدقيق",
        duration: "4 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/PDgvzKz",
        image: "assets/Courses/Cyber Threat Management.png"
    },
    cism: {
        title: "Cybersecurity Essentials",
        desc: "شهادة متقدمة في إدارة الأمن السيبراني وحوكمة المؤسسات.",
        price: "575$",
        org: "CISCO",
        level: "متوسط",
        cat: "defensive",
        req: "",
        duration: "4 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/ABErZGd",
        image: "assets/Courses/Cybersecurity Essentials.png"
    },
    ceh: {
        title: "Introduction to Modern AI",
        desc: "أساسيات الذكاء الاصطناعي التوليدي، تعلم الآلة",
        price: "٣٩٩  ريال",
        org: "CISCO",
        level: "مبتدئ",
        cat: "grc",
        req: "خبرة سنتين في الأمن",
        duration: "",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/VDBEznl",
        image: "assets/Courses/Introduction to Modern Al.png"
    },
    cisa_risk: {
        title: "CCNA: Switching, Routing, and Wireless Essentials",
        desc: "شهادة في إدارة المخاطر التقنية والرقابية للمؤسسات.",
        price: "١٬٦٩٩ ريال",
        org: "CISCO",
        level: "متوسط",
        cat: "defensive",
        req: "",
        duration: "4 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/NAOyWdY",
        image: "assets/Courses/CCNA Switching, Routing, and Wireless Essentials.png"
    },
    cysa: {
        title: "Computer Hardware Basics",
        desc: "فهم مكونات الحاسب الداخلية وتوافقها، وتعلم فكها، تركيبها، ترقيتها",
        price: "٢٧٩ ريال",
        org: "CISCO",
        level: "مبتدئ",
        cat: "defensive",
        req: "",
        duration: "3 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/mZGDyjK",
        image: "assets/Courses/Computer Hardware Basics.png"
    },
    ccsp: {
        title: "Introduction to Cybersecurity",
        desc: "رفع الوعي الأمني، وكشف أساليب الهندسة الاجتماعية والتصيد",
        price: "599$",
        org: "CISCO",
        level: "مبتدئ",
        cat: "defensive",
        req: "",
        duration: "4 أشهر",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/NAOyWdY",
        image: "assets/Courses/Introduction to Cybersecurity.png"
    },
    gcih: {
        title: "CCNA: Introduction to Networks (ITN)",
        desc: "شهادة في التعامل مع الحوادث الأمنية والاستجابة للاختراقات.",
        price: "١٬٥٩٩ ريال",
        org: "CISCO",
        level: "مبتدئ",
        cat: "defensive",
        req: "",
        duration: "5 أيام تدريب",
        lang: "English",
        cert: "نعم",
        link: "https://salla.sa/sellecm/qGXDayY",
        image: "assets/Courses/CCNA Introduction to Networks.png"
    }
};

